export const scheduleFieldInfo = {
  startTime:
    'When the first mixing step begins — autolyse if enabled, otherwise levain mix. All later steps are calculated forward from this time.',
  autolyseEnabled: 'Rest flour and water before adding salt and levain.',
  autolyseMinutes: 'Typical range is 30–60 minutes.',
  restAfterAutolyseMinutes: 'Short bench rest before incorporating levain.',
  mixMinutes: 'Time to mix levain into the dough after autolyse.',
  saltAfterLevain: 'Default order: levain first, then salt. Turn off only if you use a different incorporation order.',
  saltMixMinutes: 'Time to mix salt into the dough.',
  restAfterMixMinutes: 'Rest before bulk fermentation and folds begin.',
  slapAndFoldSlaps: 'Slap and fold happens immediately after levain mix. Use 0 to skip. A typical set is 50–100 slaps.',
  stretchAndFoldSets: 'Number of stretch-and-fold sets during bulk.',
  stretchAndFoldRestMinutes: 'Rest time between stretch-and-fold sets.',
  coilFoldSets: 'Number of coil-fold sets during bulk.',
  coilFoldRestMinutes: 'Rest time between coil-fold sets.',
  preShapeMinutesBeforeBulkEnd: 'When pre-shaping happens relative to the end of bulk.',
  shapeMinutes: 'Time blocked for final shaping at the end of bulk.',
  proofingStyle: 'Cold retard, room-temperature proof, or both in sequence.',
  coldRetardHours: 'Typical cold retard is 12–16 hours in the fridge.',
  roomProofHours: 'Default scales with room temperature — warmer rooms need less time.',
  roomFinishAfterColdHours: 'Room-temperature finish after cold retard when using both.',
  bakeMethod: 'Dutch oven or open-oven bake profile.',
  dutchOvenClosedMinutes: 'Bake with the lid on for oven spring.',
  dutchOvenLidOffMinutes: 'Bake with the lid off to set the crust.',
  dutchOvenOutOfPotMinutes: 'Finish bake outside the pot for an even crust.',
  openBakeMinutes: 'Initial open-oven bake at the higher temperature.',
  finishMinutes: 'Lower-temperature finish bake.',
  openBakeTempCelsius: 'Higher starting temperature for oven spring.',
  finishTempCelsius: 'Lower finish temperature so the crust does not burn before the crumb sets.',
} as const;
